---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: sbr-poc-appmesh
  region: ap-northeast-1

fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: default
      - namespace: kube-system
  - name: appmesh-system
    selectors:
      - namespace: appmesh-system
  - name: fp-app-pod
    selectors:
      - namespace: sbr-poc-appmesh

# https://eksctl.io/usage/eks-managed-nodegroups/
# managedNodeGroups:
#   - name: ctrl-ng-1
#     minSize: 1
#     maxSize: 3
#     desiredCapacity: 2
#     volumeSize: 20
#     labels: {role: ctrl-workers}
#     tags:
#       nodegroup-role: ctrl-workers
#     iam:
#       withAddonPolicies:
#         appMesh: true
#         albIngress: true
#         xRay: true
#         cloudWatch: true
#         certManager: true
#         autoScaler: true

# https://eksctl.io/usage/iamserviceaccounts/
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: appmesh-pod
        namespace: sbr-poc-appmesh
        labels: {aws-usage: "application"}
      attachPolicyARNs:
        - "arn:aws:iam::aws:policy/AWSAppMeshEnvoyAccess"
        - "arn:aws:iam::aws:policy/AWSCloudMapDiscoverInstanceAccess"
        - "arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess"
        - "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"
        - "arn:aws:iam::aws:policy/AWSAppMeshFullAccess"
        - "arn:aws:iam::aws:policy/AWSCloudMapFullAccess"
    - metadata:
        name: appmesh-controller
        namespace: appmesh-system
        labels: {aws-usage: "appmesh"}
      attachPolicyARNs:
        - "arn:aws:iam::aws:policy/AWSCloudMapFullAccess"
        - "arn:aws:iam::aws:policy/AWSAppMeshFullAccess"
  

# https://eksctl.io/usage/cloudwatch-cluster-logging/
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
